# This is a basic workflow to help you get started with Actions

name: CD - Apply infrastructure

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS region to apply the resources'
        required: true
        default: 'eu-central-1'

env:
  AWS_REGION: eu-central-1

jobs:
  terraform-plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      TF_VERSION: '0.14.7'
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          role-duration-seconds: 1200
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Terraform init
        run: >
          terraform init
          -backend-config=bucket=${{ secrets.TERRAFORM_BACKEND_S3_BUCKET }}
          -backend-config=key=${{ secrets.TERRAFORM_BACKEND_S3_KEY }}
          -backend-config=dynamodb_table=${{ secrets.TERRAFORM_BACKEND_DYNAMO_DB }}
          -backend-config=profile=${{ secrets.TERRAFORM_AWS_PROFILE }}
          -input=false
        working-directory: terraform
      - name: Terraform plan
        run: >
          terraform plan -out=.terraform.dev.plan.tfout
          -var region=${{ github.event.inputs.region }}
        working-directory: terraform
      - name: Terraform apply
        run: terraform apply .terraform.dev.plan.tfout
        working-directory: terraform
